### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by Sundarcj** [Spandan-Madan/DeepLearningProject#1]
Hi am new to ML, can i start with this tutorial ?
or where i have to start ? and how to start?
thanks in advance

**Comment by Spandan-Madan** [comment]
Hi @Sundarcj,

Yes I think this is a good starting point for starting out with Machine Learning. I've tried to explain everything in a lot of detail, so that might help. If you get stuck with something, you can raise a github issue here, and me or someone else who's reading the tutorials can try to answer!

Hope this helps!
