### ISSUE TITLE
Possible points of confusion and typos

### ISSUE THREAD

**Issue by dospunk** [Spandan-Madan/DeepLearningProject#21]
#### Points of confusion
- [This section](https://spandan-madan.github.io/DeepLearningProject/#What-data-is-good-data?-OR-What-do-you-mean-by-data-being-%22representative%22?) uses _f_ as the generalized function and _g_ as the exact function, whereas before _f_ was exact and _g_ was generalized. This has the potential to confuse readers.
- On `In [51]` and `In [52]`, `id` is assigned a value but does not seem to be used
- On the section after `Out [62]` it says that the shape of Y is 1666,20 but the output of `print Y.shape` is `(1595, 20)`. Where does the 1666 come from?

#### Typos
- In the last sentence of the first paragraph of [the same section](https://spandan-madan.github.io/DeepLearningProject/#What-data-is-good-data?-OR-What-do-you-mean-by-data-being-%22representative%22?), "listen to" should be changed to "watch"
- in the last paragraph before `In [68]` ([this section](https://spandan-madan.github.io/DeepLearningProject/#So,-how-do-we-store-this-movie-overview-in-a-matrix?)) "vocabular" should be "vocabulary"
- In the first paragraph of [this section](https://spandan-madan.github.io/DeepLearningProject/#The-Curse-of-Dimensionality), "can only integer values" should be "can only be integer values"
- In the second item of the first list in [this section](https://spandan-madan.github.io/DeepLearningProject/#Section-5---Non-deep,-Conventional-ML-models-with-above-data), "difference models" should be "different models"

**Comment by dospunk** [comment]
In the last sentence of the first paragraph of the same section, "listen to" should be changed to "watch"

**Comment by dospunk** [comment]
On In [52] `id` is assigned a value but does not seem to be used

**Comment by dospunk** [comment]
On the section after `Out [62]` it says that the shape of Y is 1666,20 but the output of `print Y.shape` is `(1595, 20)`. Where does the 1666 come from?

**Comment by dospunk** [comment]
`Out [55]` is not labeled

**Comment by Spandan-Madan** [comment]
These are some good points. Thanks!

People have corrected the typos through Pull Requests. If any remain, I'm sure people will spot them and create PRs. In general, I think that tiny typos matter less. Making tutorials takes a lot of time and I'd rather write more tutorials rather than spending too much time correcting for typos etc :) 

The f v/s g thing though is a great point. I'll keep that in mind in the future, thanks :)

For now, I'm closing this issue because I feel that making the above changes and rerunning all the code making sure nothing breaks will take a lot of time and the returns are small in terms of helping people's understanding of the content. Thanks for the comment though!
