### ISSUE TITLE
Would be nice to support Python 3.

### ISSUE THREAD

**Issue by andreisoare** [Spandan-Madan/DeepLearningProject#22]
Just to be clear - consider this as just a minor suggestion rather than a complaint.

Thank you for this tutorial! It's rare that people actually spend a lot of time to make a great free learning resource.

**Comment by Spandan-Madan** [comment]
Hi @andreisoare,

Yes, I agree that would have been nice! The problem is that we are relying on using a package called imdbpy for getting all our data from imdb. This package does not have python3 support. https://github.com/alberanid/imdbpy/issues/17

I could have gone around it and found a package, but there's one more problem. In my experience, installing tensorflow on python3 is a bit of a pain as it is only supported upto python3.5, while by default installing python3 gives python 3.6 on most systems. 

Python 2 was much more stable with installing tensorflow and also had support for imdbpy, to ensure minimal setup time I decided to stick to python 2! But thanks for taking out the time and making the suggestion :)
